@startuml
title Flusso Plant API - GET /v1/plants/{id}

actor Client as C
participant "Plant BS (borepurposingmgmt)" as BS
participant "Plant MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : GET /v1/plants/{id}
activate BS

note right of BS
HTTP_METHOD = GET
CONTENT_TYPE = application/json
end note

BS -> MS : GET {meRepurposingRegEndPoint}/v1/plants/{id}
activate MS

MS -> DB : Query ricerca Plant per ID
DB --> MS : Plant trovato / errore
MS --> BS : - JSON Response 200 OK: PlantDetailDTOResponse{id , name, country, nodeId, ..} \n- Error Response 400 / 404 / 500
deactivate MS

BS --> C : - 200 OK (JSON Response)\n- 400 / 404 / 500 Error response
deactivate BS

@enduml
