@startuml
title Flusso Plant API - PATCH /v1/plants/{id}

actor Client as C
participant "Plant BS (borepurposingmgmt)" as BS
participant "Plant MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : PATCH /v1/plants/{id}\nBody: PlantUpdateDTORequest {landAvailableHa, demolitionMillion, boards[], ..}
activate BS

note right of BS
HTTP_METHOD = PATCH
CONTENT_TYPE = application/json
end note

BS -> MS : PATCH {meRepurposingRegEndPoint}/v1/plants/{id}\nBody: PlantUpdateDTORequest {landAvailableHa, demolitionMillion, boards[], ..}
activate MS

MS -> DB : Aggiorna record Plant per ID
DB --> MS : Esito aggiornamento OK / errore
MS --> BS : - Response 204 NO CONTENT \n- Error Response 400 / 404 / 500
deactivate MS

BS --> C : - 204 NO CONTENT \n- 400 / 404 / 500 Error response
deactivate BS

@enduml
