@startuml
title Flusso Project API - GET /v1/projects/{projectId}

actor Client as C
participant "ProjectTask BS (borepurposingmgmt)" as API_BS
participant "ProjectTask MS (meRepurposingReg)" as API_MS
database "Database" as DB

C -> API_BS : GET /v1/projects/{projectId}
activate API_BS

note right of API_BS
HTTP_METHOD = GET
CONTENT_TYPE = application/json
Descrizione: Find project by id
Parametri:
- projectId (path, integer)
end note

API_BS -> API_MS : GET {meRepurposingRegEndPoint}/v1/projects/{projectId}
activate API_MS

API_MS -> DB : Query di ricerca del Project con projectId
DB --> API_MS : Project trovato / errore
API_MS --> API_BS : - JSON Response 200 OK : ProjectDetailDTOResponse {id, nodeId, name, plant, ...} \n- Error Response 400 / 404 / 500
deactivate API_MS

API_BS --> C : - 200 OK (JSON Response) \n- 400 / 404 / 500 Error Response
deactivate API_BS

@enduml
