@startuml
title Flusso Plant API - POST /v1/plants/search

actor Client as C
participant "Plant BS (borepurposingmgmt)" as BS
participant "Plant MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : POST /v1/plants/search\nBody: PlantSearchDTORequest {page, pageSize, sort[], ids[]}
activate BS

note right of BS
HTTP_METHOD = POST
CONTENT_TYPE = application/json
end note

BS -> MS : POST {meRepurposingRegEndPoint}/v1/plants/search\nBody: PlantSearchDTORequest {page, pageSize, sort[], ids[]}
activate MS

MS -> DB : Query di ricerca Plant con filtri  
DB --> MS : Risultato ricerca
MS --> BS : - JSON Response 200 OK: WrapperPlantDTOResponse {stats, items[] }\n- Error Response 500
deactivate MS

BS --> C : - 200 OK (JSON Response)\n- 500 Error response
deactivate BS

@enduml
