@startuml
title Flusso Counterpart API - GET /v1/counterparts/{id}

actor Client as C
participant "Counterpart BS (borepurposingmgmt)" as BS
participant "Counterpart MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : GET /v1/counterparts/{id}
activate BS

note right of BS
HTTP_METHOD = GET
CONTENT_TYPE = application/json
end note 

BS -> MS : GET {meRepurposingRegEndPoint}/v1/counterparts/{id}
activate MS

MS -> DB : Query ricerca Counterpart per ID
DB --> MS : Counterpart trovato / errore
MS --> BS : - JSON Response 200 OK : CounterpartDetailDTOResponse {id, nodeId, name, vatNumber, ..}\n- Error Response 400 / 404 / 500
deactivate MS

BS --> C : - 200 OK (JSON Response)\n- 400 / 404 / 500 Error Response
deactivate BS

@enduml
