@startuml
title Flusso Counterpart API - POST /v1/counterparts/search

actor Client as C
participant "Counterpart API BS (borepurposingmgmt)" as API_BS
participant "Counterpart Service BS (borepurposingmgmt)" as Service_BS
participant "Counterpart API MS (meRepurposingReg)" as API_MS
database "Database" as DB

== Richiesta di ricerca ==
C -> API_BS : POST /v1/counterparts/search\nBody: CounterpartSearchDTORequest { name, vatNumber, countries[], ids[], ..}
activate API_BS

API_BS -> Service_BS : Invoca route interna SEARCH_COUNTERPART
activate Service_BS

note right of Service_BS
HTTP_METHOD = POST
CONTENT_TYPE = application/json
end note

Service_BS -> API_MS : POST  {meRepurposingRegEndPoint}/v1/counterparts/search \nRequest: CounterpartSearchDTORequest { name, vatNumber, countries[], ids[], ..}
activate API_MS

API_MS -> DB : Esegue query di ricerca su Counterpart (applica filtri e paginazione)
DB --> API_MS : Risultato ricerca
API_MS --> Service_BS : - JSON Response 200 OK: WrapperCounterpartDTOResponse { items[], totalPages, pageSize, ..} \n- Error Response 404 / 500
deactivate API_MS

Service_BS --> API_BS : Restituisce i risultati della ricerca
deactivate Service_BS

API_BS --> C : - 200 OK (JSON Response) \n- 404 / 500 Error Response
deactivate API_BS

@enduml
