@startuml
title Flusso Counterpart API - POST /v1/counterparts/search

actor Client as C
participant "Counterpart BS (borepurposingmgmt)" as BS
participant "Counterpart MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : POST /v1/counterparts/search\nBody: CounterpartSearchDTORequest { name, vatNumber, countries[], ids[], ..}
activate BS

note right of BS
HTTP_METHOD = POST
CONTENT_TYPE = application/json
end note

BS -> MS : POST  {meRepurposingRegEndPoint}/v1/counterparts/search \nRequest: CounterpartSearchDTORequest { name, vatNumber, countries[], ids[], ..}
activate MS

MS -> DB : Esegue query di ricerca su Counterpart (applica filtri e paginazione)
DB --> MS : Risultato ricerca
MS --> BS : - JSON Response 200 OK: WrapperCounterpartDTOResponse { items[], totalPages, pageSize, ..} \n- Error Response 500
deactivate MS

BS --> C : - 200 OK (JSON Response) \n- 500 Error Response
deactivate BS

@enduml
