@startuml
title Flusso Counterpart API - DELETE /v1/counterparts/{id}

actor Client as C
participant "Counterpart BS (borepurposingmgmt)" as BS
participant "Counterpart MS (meRepurposingReg)" as MS
database "Database" as DB

C -> BS : DELETE /v1/counterparts/{id}
activate BS

note right of BS
HTTP_METHOD = DELETE
CONTENT_TYPE = application/json
end note

BS -> MS : DELETE {meRepurposingRegEndPoint}/v1/counterparts/{id}
activate MS

MS -> DB : Query di eliminazione Counterpart
DB --> MS : Esito eliminazione OK / errore
MS --> BS : - 204 NO CONTENT \n- Error Response 400 / 404 / 409 / 500 
deactivate MS

BS --> C : - 204 NO CONTENT \n- 400 / 404 / 409 / 500 Error Response 
deactivate BS

@enduml
