@startuml
title Flusso Counterpart API - PATCH /v1/counterparts/{id}

actor Client as C
participant "Counterpart BS (borepurposingmgmt)" as BS
participant "Counterpart MS (meRepurposingReg)" as MS
participant "DocumentNode MS (meEcDocument)" as DMS
database "Database" as DB

== Richiesta di aggiornamento ==
C -> BS : PATCH /v1/counterparts/{id}\nBody: CounterpartDTORequest {name, vatNumber, country, registeredOffice, ...}
activate BS

note right of BS
Il JSON CounterpartDTORequest viene
wrappato per l'update multiplo ->
WrapperCounterpartUpdateDTORequest
end note

note right of BS
HTTP_METHOD = PATCH
CONTENT_TYPE = application/json
end note

BS -> MS : PATCH {meRepurposingRegEndPoint}/v1/counterparts/multi\nBody: WrapperCounterpartUpdateDTORequest { items[] }
activate MS

MS -> DB : Aggiorna record Counterpart
DB --> MS : Esito aggiornamento OK / errore
MS --> BS : - 204 NO CONTENT \n- 400 / 404 / 500 Error Response
deactivate MS

== Flusso asincrono: aggiornamento nodo documento ==
note right of BS
Inizio del processo asincrono
end note

BS -> BS : CHECK_UPDATE_NODE_FOR_UPDATE_COUNTERPART
activate BS

BS -> MS : GET {meRepurposingRegEndPoint}/v1/counterparts/{id}
activate MS
MS -> DB : Ricerca Counterpart per ID
DB --> MS : Esito ricerca OK / errore
MS --> BS : - 200 OK JSON Response CounterpartDetailDTOResponse { id, name, nodeId, .. } \n- 400 / 404 / 500 Error response
deactivate MS

note right of BS
Valuta se il node è da rinominare o da spostare
in base alle variazioni di name e/o country di Counterpart
end note
alt Node da rinominare
    BS -> DMS : RENAME_NODE
    activate DMS
    DMS -> DMS : UPDATE_NODE \nPUT /v1/documents/nodes/{nodeId}\nBody: UpdateNodeDTORequest{newValue, operationType}
    DMS --> BS : 2xx Success, 4xx / 5xx Error
    deactivate DMS
else Node da spostare
    BS -> DMS : MOVE_NODE
    activate DMS
    DMS -> DMS : UPDATE_NODE \nPUT /v1/documents/nodes/{nodeId}\nBody: UpdateNodeDTORequest{newValue, operationType}
    DMS --> BS : 2xx Success, 4xx / 5xx Error
    deactivate DMS
else Nessuna modifica necessaria
    note right of BS
    Nessuna azione sul nodo documento.
    end note
end

deactivate BS

== Risposta al client ==
BS --> C : - 204 NO CONTENT \n- 400 / 404 / 500 Error Response
deactivate BS

@enduml
